# Generated by Django 4.2.8 on 2023-12-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='prosper', max_length=200),
            preserve_default=False,
        ),
    ]
