# Generated by Django 4.2.8 on 2024-04-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('Engr.', 'Engr.'), ('Prof.', 'Prof')], default='Engr.', max_length=100),
        ),
    ]
