# Generated by Django 4.2.8 on 2024-06-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_lecturer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('Engr.', 'Engr.'), ('Prof.', 'Prof'), ('Dr.', 'Dr.')], default='Engr.', max_length=100),
        ),
    ]
