# Generated by Django 4.2.8 on 2024-06-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_bio_alter_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering')], default='Electrical & Electronics Engineering', max_length=200),
        ),
    ]
