# Generated by Django 4.2.8 on 2024-02-14 21:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=4)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
