# Generated by Django 4.2.8 on 2024-02-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
