# Generated by Django 4.2.8 on 2024-02-14 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_students'),
        ('books', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
