# Generated by Django 4.2.8 on 2024-04-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course.jpg', upload_to='course_image'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], default='First Semester', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4'), ('Year 5', 'Year 5')], default='Year 5', max_length=100),
        ),
    ]
