# Generated by Django 4.2.8 on 2024-06-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online')], default='Physical', max_length=30),
        ),
    ]
