# Generated by Django 4.2.8 on 2024-07-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
