# Generated by Django 4.2.8 on 2024-08-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coursematerials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerials',
            options={'verbose_name_plural': 'Course Materials'},
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
